services:
  mongo:
    image: mongo:4.4.18
    container_name: linkvids-mongodb
    restart: always
    # 1. Define the Root User Credentials
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 9rQJy59VOuf4
    ports:
      - "3505:27017"
    volumes:
      - ./mongo_data:/data/db
    networks:         
      - default
  server:
    image: linkvids-server:latest
    container_name: linkvids-server
    restart: always
    network_mode: "host"
   # ports:
   #   - "3500:3500"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    #networks:         
    #  - default

  client:
    image: linkvids-client:latest
    build:
      context: ./client
      args:
        - VITE_API_URL=https://hub-api.linkvids.io/api
    container_name: linkvids-client
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - server
    networks:        
      - default
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1400"