version: '3.8'

services:
  server:
    image: linkvids-server:latest
    container_name: linkvids-server
    restart: always
    ports:
      - "3500:3500"
    env_file:
      - ./server/.env

  client:
    image: linkvids-client:latest
    container_name: linkvids-client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server